name: correction_auto
description: Application mobile pour la correction automatisée de copies d'élèves.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0
  lottie: ^2.7.0
  
  # Architecture & State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Camera & Image Processing
  camera: ^0.10.5+9
  image: ^4.1.3
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  
  # OCR & ML
  google_ml_kit: ^0.16.3
  google_mlkit_text_recognition: ^0.11.0
  tflite_flutter: ^0.10.4
  
  # Database
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  
  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  logger: ^2.0.2+1
  uuid: ^4.3.1
  
  # Export & Share
  pdf: ^3.10.7
  share_plus: ^7.2.1
  csv: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  drift_dev: ^2.14.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/models/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
