// This file will be generated by injectable_generator package
// After running the build_runner. For now, we create a placeholder.

import 'package:get_it/get_it.dart';

// This file will be auto-generated
GetIt init(GetIt getIt) {
  // Temporary implementation until we generate the real thing
  return getIt;
}
